name: backend
channels:
  - conda-forge
  - defaults
dependencies:
  - psycopg2=2.9.3
  - passlib=1.7.4
  - flask=2.0.2
  - flask-jwt-extended=4.3.1
  - pyjwt=2.3.0
  - pytest=6.2.5
  - python-dotenv=0.19.2
  - pip
  - pylint=2.12.2
  - email_validator=1.1.3
  - gunicorn=20.1.0
  - beautifulsoup4==4.10.0
  - requests==2.27.1
