# This is a basic workflow to help you get started with Actions

name: CICD-frontend
env:
  AWS_REGION_NAME          : "us-west-1"
  SOURCE_PATH : "/*"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
    paths:
      - 'dist/**.js'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cd_pipeline_frontend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      
      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id : ${{ secrets.SS_AWS_ACCESS_KEY }}
          aws-secret-access-key : ${{ secrets.SS_AWS_SECRET_KEY }}
          aws-region : ${{ env.AWS_REGION_NAME }}

      - name: Upload deployment package to S3
        run: aws s3 sync dist/ s3://socialstock-frontend --acl public-read
      
      - name: Invalidate cloudfront distribution
        uses: awact/cloudfront-action@master
        env:
          SOURCE_PATH: ${{ env.SOURCE_PATH }}
          AWS_REGION: ${{ env.AWS_REGION_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.SS_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SS_AWS_SECRET_KEY }}
          DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
        
