# This is a basic workflow to help you get started with Actions

name: CICD-frontend
env:
  EB_PACKAGE_S3_BUCKET_NAME : "socialstock-frontend"
  AWS_REGION_NAME          : "us-west-1"
  SOURCE_PATH: './*'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
    - 'frontend/**.js'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cd_pipeline_frontend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      
      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id : ${{ secrets.SS_AWS_ACCESS_KEY }}
          aws-secret-access-key : ${{ secrets.SS_AWS_SECRET_KEY }}
          aws-region : ${{ env.AWS_REGION_NAME }}

      - name: Upload deployment package to S3
        run: aws s3 cp ./dist/* s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
      
      - name: Invalidate cloudfront distribution
        run: aws cloudfront create-invalidation \
             --distribution-id ${{ secrets.DISTRIBUTION_ID }} \
             --paths ${{ env.SOURCE_PATH }}
        
